### ISSUE TITLE
ng-show and ng-hide are not working on <li> elements

### ISSUE THREAD

**Issue by saurabhSiddhu** [digitalfondue/df-tab-menu#12]

**Comment by renilbabu03** [comment]
Yes....I am also having the same problem...wondering if anyone could sort the thing out....

**Comment by saurabhSiddhu** [comment]
Can anybody help me out

**Comment by erost** [comment]
This is probably a limitation of the library. I'm not exactly sure what you are trying to do as you haven't posted any code example, but in our examples there is a menu built using ng-repeat and a list of menu items: as a workaround, you can achieve the equivalent of ng-show/ng-hide by filtering on the array of elements.

**Comment by saurabhSiddhu** [comment]
Thank you  for your answer and directive . Is there any way to use your directive with ngSwitch tabs ?
